version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      config: ".eslintrc.json"
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
exclude_patterns:
  - "assets/scripts/vendor/*.js"
  - "test/integration/smoke.spec.js"
  - "**/__tests__"
  - "**/__mocks__"
  - "docs/**/*.rst"
  - "assets/scripts/dialogs/GeotagDialog.jsx"
checks:
  file-lines:
    config:
      threshold: 250
  method-lines:
    config:
      threshold: 100
  similar-code:
    config:
      threshold: 60
