import reducer, {
  resetUndoStack,
  replaceUndoStack,
  createNewUndo,
  undo,
  redo,
  MAX_UNDO_LIMIT,
} from './history'

describe('undo reducer', () => {
  const initialState = {
    stack: [],
    position: null,
  }

  it('should handle initial state', () => {
    expect(reducer(undefined, { type: 'test' })).toEqual(initialState)
  })

  it('should handle resetUndoStack()', () => {
    expect(
      reducer(
        {
          stack: [{}, {}, {}],
          position: 1,
        },
        resetUndoStack()
      )
    ).toEqual(initialState)
  })

  it('should handle replaceUndoStack()', () => {
    expect(
      reducer(
        {
          stack: [{ a: [1] }, { b: [2] }, { c: [3] }],
          position: 2,
        },
        replaceUndoStack({
          stack: [{ a: [1] }, { b: [2] }],
          position: 2,
        })
      )
    ).toEqual({
      stack: [{ a: [1] }, { b: [2] }],
      // Stack position must actually be within length of new stack
      position: 1,
    })
  })

  // Many of the following tests were generated by Claude early in the
  // history rework process and seem weird and off

  it('should handle createNewUndo()', () => {
    const entry = { name: ['after'] }

    expect(reducer(initialState, createNewUndo(entry))).toEqual({
      stack: [entry],
      position: 0,
    })
  })

  it('creates a new undo at the top of an existing stack', () => {
    const item = { idx: [10] }
    const state = reducer(
      {
        position: 9,
        stack: Array(10)
          .fill({})
          .map((_, i) => ({ idx: [i] })),
      },
      createNewUndo(item)
    )

    expect(state.position).toEqual(10)
    expect(state.stack.length).toEqual(11)
    expect(state.stack[state.stack.length - 1]).toMatchObject(item)
  })

  it('truncates an undo stack if a new undo state is created at an earlier position', () => {
    const item = { idx: [99] }
    const state = reducer(
      {
        position: 6,
        stack: Array(10)
          .fill({})
          .map((_, i) => ({ idx: [i] })),
      },
      createNewUndo(item)
    )

    // Expect the position to point to the newly added item
    expect(state.position).toEqual(7)

    // Expect the stack to be truncated and then appended by one item
    expect(state.stack.length).toEqual(8)

    // Expect the last item on the stack to match what was added
    expect(state.stack[state.stack.length - 1]).toMatchObject(item)
  })

  it('trims an undo stack that is too large', () => {
    const item = { idx: [999] }
    const state = reducer(
      {
        position: MAX_UNDO_LIMIT - 1,
        stack: Array(MAX_UNDO_LIMIT)
          .fill({})
          .map((_, i) => ({ idx: [i] })),
      },
      createNewUndo(item)
    )

    // Stack size should max at MAX_UNDO_LIMIT
    expect(state.stack.length).toEqual(MAX_UNDO_LIMIT)

    // Position should point to the final item in the stack
    expect(state.position).toEqual(MAX_UNDO_LIMIT - 1)

    // Expect the last item on the stack to match what was added
    expect(state.stack[MAX_UNDO_LIMIT - 1]).toMatchObject(item)
  })

  it('decreases position by 1 for undo', () => {
    const state = reducer(
      {
        position: 9,
        stack: Array(10)
          .fill({})
          .map((_, i) => ({ idx: [i] })),
      },
      undo()
    )

    expect(state.position).toEqual(8)

    const state2 = reducer(state, undo())
    expect(state2.position).toEqual(7)
  })

  it('increases position by 1 for redo', () => {
    const state = reducer(
      {
        position: 2,
        stack: Array(10)
          .fill({})
          .map((_, i) => ({ idx: [i] })),
      },
      redo()
    )

    expect(state.position).toEqual(3)

    const state2 = reducer(state, redo())
    expect(state2.position).toEqual(4)
  })
})
