import { screen } from '@testing-library/react'
import { userEvent } from '@testing-library/user-event'
import { vi } from 'vitest'

import { render } from '~/test/helpers/render.js'
import { fetchGalleryPage } from '~/src/store/actions/gallery.js'
import { GalleryPagination } from './GalleryPagination.js'

vi.mock('~/src/store/actions/gallery.js', () => ({
  fetchGalleryPage: vi.fn((page: number) => ({
    type: 'MOCK_FETCH_GALLERY_PAGE',
    payload: page,
  })),
}))

// Generated by Claude
function buildState({
  page = 1,
  total = 0,
  totalPages = 1,
  hasNextPage = false,
  hasPreviousPage = false,
  streetCount = 0,
}: {
  page?: number
  total?: number
  totalPages?: number
  hasNextPage?: boolean
  hasPreviousPage?: boolean
  streetCount?: number
}) {
  return {
    app: {
      contentDirection: 'ltr',
    },
    gallery: {
      streets: Array.from({ length: streetCount }, (_, index) => ({
        id: `street-${index}`,
      })),
      pagination: {
        page,
        limit: 100,
        total,
        totalPages,
        hasNextPage,
        hasPreviousPage,
      },
    },
  }
}

describe('GalleryPagination', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('displays "No streets yet" when totalPages is 0', () => {
    render(<GalleryPagination isLoading={false} />, {
      initialState: buildState({ totalPages: 0, streetCount: 0 }),
    })

    expect(screen.getByText(/No streets yet/i)).toBeInTheDocument()
  })

  it('displays "X streets" when totalPages is 1', () => {
    render(<GalleryPagination isLoading={false} />, {
      initialState: buildState({ totalPages: 1, streetCount: 4 }),
    })

    expect(screen.getByText('4 streets')).toBeInTheDocument()
  })

  it('displays first-page pagination text when totalPages is greater than 1', () => {
    render(<GalleryPagination isLoading={false} />, {
      initialState: buildState({
        page: 1,
        total: 250,
        totalPages: 3,
        streetCount: 100,
      }),
    })

    expect(screen.getByText('1–100 of 250 streets')).toBeInTheDocument()
  })

  it('displays later-page pagination text when totalPages is greater than 1', () => {
    render(<GalleryPagination isLoading={false} />, {
      initialState: buildState({
        page: 3,
        total: 250,
        totalPages: 3,
        streetCount: 50,
      }),
    })

    expect(screen.getByText('201–250 of 250 streets')).toBeInTheDocument()
  })

  it('fires fetch action for previous and next buttons', async () => {
    render(<GalleryPagination isLoading={false} />, {
      initialState: buildState({
        page: 2,
        total: 300,
        totalPages: 3,
        hasNextPage: true,
        hasPreviousPage: true,
        streetCount: 100,
      }),
    })

    await userEvent.click(screen.getByRole('button', { name: 'Previous page' }))
    await userEvent.click(screen.getByRole('button', { name: 'Next page' }))

    expect(fetchGalleryPage).toHaveBeenNthCalledWith(1, 1)
    expect(fetchGalleryPage).toHaveBeenNthCalledWith(2, 3)
  })
})
