import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  contributingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'contributing'
    }
  ],
  userGuideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user-guide'
    }
  ]
}

export default sidebars
